{
 "title": "java prometheus integration",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "% of Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*_job_completed_total\"}[$__range])) / (sum(max_over_time({__name__=~\".*_job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*_job_failed_total\"}[$__range]))) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Jobs Failed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*_job_failed_total\"}[$__range])) / (sum(max_over_time({__name__=~\".*_job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*_job_failed_total\"}[$__range]))) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Petrol Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*petrol_job_completed_total\"}[$__range])) / sum(max_over_time({__name__=~\".*petrol_job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*petrol_job_failed_total\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Hybrid Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*hybrid_job_completed_total\"}[$__range])) / sum(max_over_time({__name__=~\".*hybrid_job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*hybrid_job_failed_total\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of CNG Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*cng_job_completed_total\"}[$__range])) / sum(max_over_time({__name__=~\".*cng_job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*cng_job_failed_total\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job duration in table",
   "type": "table",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "last_over_time({__name__=~\".*_job_duration_seconds\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Status & Last Execution Time",
   "type": "table",
   "gridPos": { "h": 17, "w": 9, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "last_over_time({__name__=~\".*_job_status\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job duration as bar gauge",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\".*_job_duration_seconds\"}[$__range]",
     "legendFormat": "{{jobname}}"
    }
   ]
  },
  {
   "title": "Job duration as time series",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{__name=~\".*_job_duration_seconds\"}",
     "legendFormat": "{{jobname}}"
    }
   ]
  }
 ]
}