{
 "title": "java prometheus integration",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Job Status",
   "type": "table",
   "gridPos": { "h": 24, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time({__name__=~\".*_job_status\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job durations",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\".*_job_duration_seconds\"}[$__range]",
     "legendFormat": "{{jobname}}"
    }
   ]
  },
  {
   "title": "Batch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\".*_job_duration_seconds\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*_job_completed_total\"}[$__range])) / (sum(max_over_time({__name__=~\".*_job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*_job_failed_total\"}[$__range]))) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Petrol Batch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\".*petrol_job_duration_seconds\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Jobs Failed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*_job_failed_total\"}[$__range])) / (sum(max_over_time({__name__=~\".*_job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*_job_failed_total\"}[$__range]))) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hybrid Batch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\".*hybrid_job_duration_seconds\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Petrol Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*petrol_job_completed_total\"}[$__range])) / sum(max_over_time({__name__=~\".*petrol_job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*petrol_job_failed_total\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CNG Batch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\".*cng_job_duration_seconds\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Hybrid Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*hybrid_job_completed_total\"}[$__range])) / sum(max_over_time({__name__=~\".*hybrid_job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*hybrid_job_failed_total\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of CNG Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*cng_job_completed_total\"}[$__range])) / sum(max_over_time({__name__=~\".*cng_job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*cng_job_failed_total\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}