{
 "title": "java prometheus integration",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(job_duration_seconds,job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Job Status",
   "type": "table",
   "gridPos": { "h": 24, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(job_status[$__range]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job durations",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job_duration_seconds[$__range]", "legendFormat": "{{job_name}}" }
   ]
  },
  {
   "title": "Running Batches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by (job_name) (job_status) == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*job_completed_total\"}[$__range])) / (sum(max_over_time({__name__=~\".*job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*job_failed_total\"}[$__range]))) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(job_duration_seconds[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Jobs Failed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time({__name__=~\".*job_failed_total\"}[$__range])) / (sum(max_over_time({__name__=~\".*job_completed_total\"}[$__range])) + sum(max_over_time({__name__=~\".*job_failed_total\"}[$__range]))) ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Petrol Batch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(job_duration_seconds{jobtype=\"petrol\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Petrol Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time(job_completed_total{jobtype=\"petrol\"}[$__range])) / sum(max_over_time(job_completed_total{jobtype=\"petrol\"}[$__range])) + sum(max_over_time(job_failed_total{jobtype=\"petrol\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hybrid Batch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(job_duration_seconds{jobtype=\"hybrid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Hybrid Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time(job_completed_total{jobtype=\"hybrid\"}[$__range])) / sum(max_over_time(job_completed_total{jobtype=\"hybrid\"}[$__range])) + sum(max_over_time(job_failed_total{jobtype=\"hybrid\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CNG Batch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(job_duration_seconds{jobtype=\"cng\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of CNG Jobs Completed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(max_over_time(job_completed_total{jobtype=\"cng\"}[$__range])) / sum(max_over_time(job_completed_total{jobtype=\"cng\"}[$__range])) + sum(max_over_time(job_failed_total{jobtype=\"cng\"}[$__range]))) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Diesel Batch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(job_duration_seconds{jobtype=\"diesel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EV Batch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(job_duration_seconds{jobtype=\"ev\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trend of Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(job_duration_seconds{job_name=\"$job_name\"}[1d])",
     "legendFormat": "{{job_name}}"
    }
   ]
  }
 ]
}